# Generated by Django 6.0.7 on 2026-07-30 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('suggested_action', models.TextField()),
                ('agent_type', models.CharField(max_length=60)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('rejection_note', models.TextField(blank=True, default='')),
                ('patient_name', models.CharField(blank=True, default='', max_length=120)),
                ('patient_mrn', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(max_length=30, unique=True)),
                ('action_type', models.CharField(max_length=40)),
                ('workflow', models.CharField(max_length=60)),
                ('input_ref', models.CharField(blank=True, default='', max_length=200)),
                ('model_version', models.CharField(default='helix-v2.4.1', max_length=30)),
                ('raw_output', models.TextField(blank=True, default='')),
                ('final_output', models.TextField(blank=True, default='')),
                ('confidence', models.PositiveSmallIntegerField(default=90)),
                ('confidence_tier', models.CharField(default='high', max_length=10)),
                ('risk_tier', models.CharField(default='medium', max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('reviewer_id', models.CharField(default='current-user', max_length=40)),
                ('reviewer_reason', models.TextField(blank=True, default='')),
                ('reviewer_note', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Patient', 'Patient'), ('Lead', 'Lead'), ('Employer', 'Employer')], max_length=15)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'Sms'), ('Multi-Channel', 'Multi')], default='Email', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Active', max_length=10)),
                ('audience_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('employer', models.CharField(db_index=True, max_length=100)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('classification', models.CharField(choices=[('Proactive', 'Proactive'), ('Reactive', 'Reactive')], default='Proactive', max_length=10)),
                ('awv_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Deferred', 'Deferred'), ('Rejected', 'Rejected'), ('N/A', 'Na')], default='Open', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_id', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('provider', models.CharField(max_length=80)),
                ('is_after_hours', models.BooleanField(default=False)),
                ('copay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Completed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='api.patient', to_field='mrn')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=120)),
                ('cpt_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('date_of_service', models.DateField()),
                ('rate_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Denied', 'Denied')], default='Paid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.patient', to_field='mrn')),
            ],
            options={
                'ordering': ['-date_of_service'],
            },
        ),
    ]
