export interface MipsTrendData {
  month: string;
  score: number;
}

export const MIPS_SCORE_TREND: MipsTrendData[] = [
  { month: "Jan", score: 72.0 },
  { month: "Feb", score: 85.0 },
  { month: "Mar", score: 76.0 },
  { month: "Apr", score: 80.0 },
  { month: "May", score: 88.0 },
  { month: "Jun", score: 86.0 },
  { month: "Jul", score: 87.0 },
  { month: "Aug", score: 91.0 },
  { month: "Sep", score: 86.0 },
  { month: "Oct", score: 89.0 },
  { month: "Nov", score: 85.0 },
  { month: "Dec", score: 88.0 },
];

export interface MipsCategoryData {
  name: string;
  score: number;
  maxScore: number;
  weight: string;
  color: string;
}

export const MIPS_CATEGORY_PERFORMANCE: MipsCategoryData[] = [
  { name: "Quality", score: 42.1, maxScore: 45, weight: "45%", color: "#10b981" },
  { name: "Cost", score: 16.1, maxScore: 30, weight: "30%", color: "#3b82f6" },
  { name: "PI", score: 19.1, maxScore: 25, weight: "25%", color: "#8b5cf6" },
  { name: "IA", score: 14.2, maxScore: 15, weight: "15%", color: "#f59e0b" },
];

export interface MipsProviderRow {
  id: string;
  name: string;
  specialty: string;
  avatar: string;
  avatarColor: string;
  score: number;
  quality: number;
  cost: number;
  pi: number;
  ia: number;
  trend: string;
  trendPositive: boolean;
}

export const MIPS_PROVIDERS: MipsProviderRow[] = [
  {
    id: "p1",
    name: "Dr. Amanda Johnson",
    specialty: "Neurology",
    avatar: "DAJ",
    avatarColor: "#3b82f6",
    score: 77.9,
    quality: 42.1,
    cost: 16.1,
    pi: 19.1,
    ia: 14.2,
    trend: "↑ +3.2",
    trendPositive: true,
  },
  {
    id: "p2",
    name: "Dr. Andrew Anderson",
    specialty: "Dermatology",
    avatar: "DAA",
    avatarColor: "#10b981",
    score: 91.8,
    quality: 39.0,
    cost: 18.8,
    pi: 19.2,
    ia: 14.7,
    trend: "↑ +5.1",
    trendPositive: true,
  },
  {
    id: "p3",
    name: "Dr. Laura Hill",
    specialty: "Physical Medicine",
    avatar: "DLH",
    avatarColor: "#10b981",
    score: 82.5,
    quality: 43.8,
    cost: 16.3,
    pi: 19.9,
    ia: 12.6,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p4",
    name: "Dr. Christopher Nelson",
    specialty: "Preventive Medicine",
    avatar: "DCN",
    avatarColor: "#10b981",
    score: 92.1,
    quality: 40.3,
    cost: 17.1,
    pi: 20.7,
    ia: 14.0,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p5",
    name: "Dr. Emily Lewis",
    specialty: "Radiology",
    avatar: "DEL",
    avatarColor: "#f59e0b",
    score: 84.6,
    quality: 38.1,
    cost: 14.8,
    pi: 18.5,
    ia: 13.2,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p6",
    name: "Dr. Robert Lee",
    specialty: "Internal Medicine",
    avatar: "DRL",
    avatarColor: "#10b981",
    score: 94.6,
    quality: 44.8,
    cost: 14.9,
    pi: 20.4,
    ia: 14.4,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p7",
    name: "Dr. Matthew Brown",
    specialty: "Infectious Disease",
    avatar: "DMB",
    avatarColor: "#f59e0b",
    score: 85.2,
    quality: 39.1,
    cost: 14.9,
    pi: 18.7,
    ia: 12.4,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p8",
    name: "Dr. Jason Martinez",
    specialty: "Cardiology",
    avatar: "DJM",
    avatarColor: "#10b981",
    score: 93.2,
    quality: 38.9,
    cost: 17.0,
    pi: 21.5,
    ia: 12.9,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p9",
    name: "Dr. Lisa Adams",
    specialty: "Endocrinology",
    avatar: "DLA",
    avatarColor: "#10b981",
    score: 90.1,
    quality: 41.7,
    cost: 15.9,
    pi: 18.4,
    ia: 14.1,
    trend: "↓ -1.0",
    trendPositive: false,
  },
  {
    id: "p10",
    name: "Dr. Ashley Hill",
    specialty: "Pediatrics",
    avatar: "DAH",
    avatarColor: "#f59e0b",
    score: 90.6,
    quality: 39.7,
    cost: 15.4,
    pi: 20.7,
    ia: 14.8,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p11",
    name: "Dr. Kevin Taylor",
    specialty: "Sports Medicine",
    avatar: "DKT",
    avatarColor: "#f59e0b",
    score: 85.5,
    quality: 44.7,
    cost: 15.6,
    pi: 20.3,
    ia: 14.8,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p12",
    name: "Dr. David Carter",
    specialty: "Surgery",
    avatar: "DDC",
    avatarColor: "#10b981",
    score: 90.8,
    quality: 42.9,
    cost: 15.2,
    pi: 22.4,
    ia: 14.2,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p13",
    name: "Dr. Steven Walker",
    specialty: "Preventive Medicine",
    avatar: "DSW",
    avatarColor: "#10b981",
    score: 88.3,
    quality: 38.5,
    cost: 16.2,
    pi: 20.6,
    ia: 13.0,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p14",
    name: "Dr. Ryan Nelson",
    specialty: "Anesthesiology",
    avatar: "DRN",
    avatarColor: "#f59e0b",
    score: 91.3,
    quality: 41.3,
    cost: 18.7,
    pi: 18.9,
    ia: 12.5,
    trend: "↓ -1.0",
    trendPositive: false,
  },
  {
    id: "p15",
    name: "Dr. Ryan Miller",
    specialty: "Cardiology",
    avatar: "DRM",
    avatarColor: "#10b981",
    score: 82.2,
    quality: 40.5,
    cost: 16.6,
    pi: 20.3,
    ia: 14.9,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p16",
    name: "Dr. Laura Nelson",
    specialty: "Radiology",
    avatar: "DLN",
    avatarColor: "#10b981",
    score: 84.3,
    quality: 26.4,
    cost: 18.5,
    pi: 22.9,
    ia: 13.5,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p17",
    name: "Dr. Steven Davis",
    specialty: "Critical Care",
    avatar: "DSD",
    avatarColor: "#10b981",
    score: 87.9,
    quality: 40.1,
    cost: 15.3,
    pi: 18.2,
    ia: 14.3,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p18",
    name: "Dr. Jennifer Davis",
    specialty: "Sleep Medicine",
    avatar: "DJD",
    avatarColor: "#f59e0b",
    score: 92.1,
    quality: 42.8,
    cost: 15.8,
    pi: 21.0,
    ia: 12.5,
    trend: "↓ -1.0",
    trendPositive: false,
  },
  {
    id: "p19",
    name: "Dr. Steven Lopez",
    specialty: "Surgery",
    avatar: "DSL",
    avatarColor: "#10b981",
    score: 80.8,
    quality: 40.0,
    cost: 14.5,
    pi: 23.6,
    ia: 12.7,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p20",
    name: "Dr. Joshua Nelson",
    specialty: "Pediatrics",
    avatar: "DJN",
    avatarColor: "#f59e0b",
    score: 82.6,
    quality: 29.9,
    cost: 15.6,
    pi: 22.4,
    ia: 14.8,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p21",
    name: "Dr. Marie Chen",
    specialty: "Pain Management",
    avatar: "DMC",
    avatarColor: "#10b981",
    score: 100.0,
    quality: 43.6,
    cost: 19.7,
    pi: 24.4,
    ia: 12.6,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p22",
    name: "Dr. Samantha Nelson",
    specialty: "Anesthesiology",
    avatar: "DSN",
    avatarColor: "#10b981",
    score: 100.0,
    quality: 44.6,
    cost: 18.7,
    pi: 23.5,
    ia: 13.7,
    trend: "↓ -1.0",
    trendPositive: false,
  },
  {
    id: "p23",
    name: "Dr. Emily Carter",
    specialty: "Endocrinology",
    avatar: "DEC",
    avatarColor: "#f59e0b",
    score: 82.0,
    quality: 40.7,
    cost: 15.4,
    pi: 21.1,
    ia: 14.8,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p24",
    name: "Dr. Nicole Lee",
    specialty: "Cardiology",
    avatar: "DNL",
    avatarColor: "#10b981",
    score: 84.4,
    quality: 41.3,
    cost: 18.0,
    pi: 22.5,
    ia: 12.6,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p25",
    name: "Dr. Robert Perez",
    specialty: "Cardiology",
    avatar: "DRP",
    avatarColor: "#f59e0b",
    score: 95.9,
    quality: 40.9,
    cost: 19.4,
    pi: 23.6,
    ia: 13.0,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p26",
    name: "Dr. Nicole King",
    specialty: "Family Medicine",
    avatar: "DNK",
    avatarColor: "#f59e0b",
    score: 87.4,
    quality: 40.8,
    cost: 15.0,
    pi: 19.4,
    ia: 12.2,
    trend: "↓ -1.0",
    trendPositive: false,
  },
  {
    id: "p27",
    name: "Dr. Samantha Clark",
    specialty: "Cardiology",
    avatar: "DSC",
    avatarColor: "#10b981",
    score: 93.1,
    quality: 42.5,
    cost: 18.0,
    pi: 19.1,
    ia: 12.5,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p28",
    name: "Dr. Sarah Johnson",
    specialty: "Pathology",
    avatar: "DSJ",
    avatarColor: "#f59e0b",
    score: 93.7,
    quality: 43.6,
    cost: 16.3,
    pi: 20.3,
    ia: 13.5,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p29",
    name: "Dr. Rachel Thompson",
    specialty: "Infectious Disease",
    avatar: "DRT",
    avatarColor: "#f59e0b",
    score: 93.5,
    quality: 43.2,
    cost: 15.9,
    pi: 20.8,
    ia: 13.6,
    trend: "↓ -1.8",
    trendPositive: false,
  },
  {
    id: "p30",
    name: "Dr. Nicole Brown",
    specialty: "Gastroenterology",
    avatar: "DNB",
    avatarColor: "#f59e0b",
    score: 97.1,
    quality: 41.4,
    cost: 18.9,
    pi: 24.4,
    ia: 12.5,
    trend: "↓ -1.0",
    trendPositive: false,
  },
];

export interface MipsMeasureItem {
  id: string;
  name: string;
  cmsCode: string;
  priority: string;
  rate: string;
  scoreBadge: string;
  colorClass: string;
  type?: string;
  benchmark?: string;
}

export const MIPS_QUALITY_MEASURES: MipsMeasureItem[] = [
  {
    id: "bp",
    name: "Controlling Blood Pressure",
    cmsCode: "CMS161v11",
    priority: "Medium Priority",
    type: "Outcome",
    benchmark: "70.0%",
    rate: "92.8%",
    scoreBadge: "8",
    colorClass: "border-emerald-500 text-emerald-600 dark:text-emerald-400 bg-emerald-50/40 dark:bg-emerald-950/20",
  },
  {
    id: "diabetes",
    name: "Diabetes HbA1c Control (< 8%)",
    cmsCode: "CMS122v11",
    priority: "High Priority",
    type: "Intermediate Outcome",
    benchmark: "65.0%",
    rate: "68.4%",
    scoreBadge: "5",
    colorClass: "border-amber-500 text-amber-600 dark:text-amber-400 bg-amber-50/40 dark:bg-amber-950/20",
  },
  {
    id: "depression",
    name: "Depression Remission at 12 Months",
    cmsCode: "CMS159v11",
    priority: "High Priority",
    type: "Outcome",
    benchmark: "40.0%",
    rate: "81.5%",
    scoreBadge: "7",
    colorClass: "border-emerald-500 text-emerald-600 dark:text-emerald-400 bg-emerald-50/40 dark:bg-emerald-950/20",
  },
  {
    id: "screening",
    name: "Breast Cancer Screening",
    cmsCode: "CMS125v10",
    priority: "Low Priority",
    type: "Process / Structure",
    benchmark: "80.0%",
    rate: "88.3%",
    scoreBadge: "8",
    colorClass: "border-emerald-500 text-emerald-600 dark:text-emerald-400 bg-emerald-50/40 dark:bg-emerald-950/20",
  },
];

export interface MipsActivityItem {
  id: string;
  name: string;
  code: string;
  weight: string;
  status: "Complete" | "In Progress";
}

export const MIPS_IMPROVEMENT_ACTIVITIES: MipsActivityItem[] = [
  {
    id: "rx-mgmt",
    name: "Medication Management",
    code: "IA_EPA_4",
    weight: "High Weight",
    status: "Complete",
  },
  {
    id: "care-coord",
    name: "Care Coordination",
    code: "IA_CC_1",
    weight: "Low Weight",
    status: "Complete",
  },
  {
    id: "pt-eng",
    name: "Patient Engagement",
    code: "IA_BE_2",
    weight: "Medium Weight",
    status: "In Progress",
  },
];
